--
-- PostgreSQL database dump
--

\restrict O6BK9XoUyBC1GMh5NzAAP40OAn8ANpLhLV518kGEVcQ1kyDwpS0AxTEfHfH9PvQ

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: core_alimentacio; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_alimentacio (
    id bigint NOT NULL,
    tipus_alimentacio character varying(15) NOT NULL,
    calories smallint NOT NULL,
    proteina smallint NOT NULL,
    carbohidrats smallint NOT NULL,
    grases smallint NOT NULL,
    suplementacio text,
    atleta_id character varying(20) NOT NULL,
    CONSTRAINT core_alimentacio_calories_check CHECK ((calories >= 0)),
    CONSTRAINT core_alimentacio_carbohidrats_check CHECK ((carbohidrats >= 0)),
    CONSTRAINT core_alimentacio_grases_check CHECK ((grases >= 0)),
    CONSTRAINT core_alimentacio_proteina_check CHECK ((proteina >= 0))
);


ALTER TABLE practica.core_alimentacio OWNER TO est_e7864955;

--
-- Name: core_alimentacio_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_alimentacio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_alimentacio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_atleta; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_atleta (
    dni_atleta character varying(20) NOT NULL,
    nom character varying(100) NOT NULL,
    data_naixement date NOT NULL,
    correu character varying(150) NOT NULL,
    numero_telefon character varying(20) NOT NULL,
    pes numeric(5,2) NOT NULL,
    composicio_corporal character varying(200) NOT NULL,
    altura numeric(3,2) NOT NULL,
    objectiu character varying(100) NOT NULL,
    activitat_fisica_diaria character varying(15) NOT NULL,
    estat character varying(10) NOT NULL
);


ALTER TABLE practica.core_atleta OWNER TO est_e7864955;

--
-- Name: core_descans; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_descans (
    id bigint NOT NULL,
    data_inici timestamp with time zone NOT NULL,
    duracio smallint NOT NULL,
    despert smallint NOT NULL,
    rem smallint NOT NULL,
    core smallint NOT NULL,
    deep smallint NOT NULL,
    hrv smallint NOT NULL,
    atleta_id character varying(20) NOT NULL,
    CONSTRAINT core_descans_core_check CHECK ((core >= 0)),
    CONSTRAINT core_descans_deep_check CHECK ((deep >= 0)),
    CONSTRAINT core_descans_despert_check CHECK ((despert >= 0)),
    CONSTRAINT core_descans_duracio_check CHECK ((duracio >= 0)),
    CONSTRAINT core_descans_hrv_check CHECK ((hrv >= 0)),
    CONSTRAINT core_descans_rem_check CHECK ((rem >= 0))
);


ALTER TABLE practica.core_descans OWNER TO est_e7864955;

--
-- Name: core_descans_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_descans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_descans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_exercici; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_exercici (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    descripcio text,
    descans_entre_series interval,
    atleta_id character varying(20) NOT NULL
);


ALTER TABLE practica.core_exercici OWNER TO est_e7864955;

--
-- Name: core_exercici_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_exercici ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_exercici_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_forca; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_forca (
    id bigint NOT NULL,
    num_serie smallint NOT NULL,
    grup_muscular character varying(100) NOT NULL,
    pes numeric(5,2) NOT NULL,
    rpe smallint NOT NULL,
    exercici_id bigint NOT NULL,
    CONSTRAINT core_forca_num_serie_check CHECK ((num_serie >= 0)),
    CONSTRAINT core_forca_rpe_check CHECK ((rpe >= 0))
);


ALTER TABLE practica.core_forca OWNER TO est_e7864955;

--
-- Name: core_forca_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_forca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_forca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_informeia; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_informeia (
    id bigint NOT NULL,
    recomanacio_entrenament text NOT NULL,
    recomanacio_alimentacio text NOT NULL,
    recomanacio_descans text NOT NULL,
    registre_diari_id bigint NOT NULL
);


ALTER TABLE practica.core_informeia OWNER TO est_e7864955;

--
-- Name: core_informeia_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_informeia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_informeia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_lesio; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_lesio (
    id bigint NOT NULL,
    data_inici date NOT NULL,
    data_fi date,
    zona_afectada character varying(100) NOT NULL,
    grau_serietat smallint NOT NULL,
    estat_actual character varying(15) NOT NULL,
    comentaris_diagnostic text,
    atleta_id character varying(20) NOT NULL,
    CONSTRAINT core_lesio_grau_serietat_check CHECK ((grau_serietat >= 0))
);


ALTER TABLE practica.core_lesio OWNER TO est_e7864955;

--
-- Name: core_lesio_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_lesio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_lesio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_registrediari; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_registrediari (
    id bigint NOT NULL,
    data date NOT NULL,
    adaptabilitat_alimentacio smallint NOT NULL,
    estat_recuperacio_descans double precision NOT NULL,
    nivell_energia double precision NOT NULL,
    nivell_estres double precision NOT NULL,
    comentaris_entrenaments text,
    sensacions_generals text,
    atleta_id character varying(20) NOT NULL,
    CONSTRAINT core_registrediari_adaptabilitat_alimentacio_check CHECK ((adaptabilitat_alimentacio >= 0))
);


ALTER TABLE practica.core_registrediari OWNER TO est_e7864955;

--
-- Name: core_registrediari_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_registrediari ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_registrediari_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_resistencia; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_resistencia (
    id bigint NOT NULL,
    num_serie smallint NOT NULL,
    duracio interval NOT NULL,
    tipus_superficie character varying(10) NOT NULL,
    distancia double precision NOT NULL,
    desnivell smallint,
    freq_cardiaca_mitjana smallint NOT NULL,
    exercici_id bigint NOT NULL,
    CONSTRAINT core_resistencia_desnivell_check CHECK ((desnivell >= 0)),
    CONSTRAINT core_resistencia_freq_cardiaca_mitjana_check CHECK ((freq_cardiaca_mitjana >= 0)),
    CONSTRAINT core_resistencia_num_serie_check CHECK ((num_serie >= 0))
);


ALTER TABLE practica.core_resistencia OWNER TO est_e7864955;

--
-- Name: core_resistencia_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_resistencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_resistencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_sessioentrenament; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_sessioentrenament (
    id bigint NOT NULL,
    data date NOT NULL,
    duracio_total interval NOT NULL,
    comentaris text,
    atleta_id character varying(20) NOT NULL,
    ubicacio_id bigint NOT NULL
);


ALTER TABLE practica.core_sessioentrenament OWNER TO est_e7864955;

--
-- Name: core_sessioentrenament_exercicis; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_sessioentrenament_exercicis (
    id bigint NOT NULL,
    sessioentrenament_id bigint NOT NULL,
    exercici_id bigint NOT NULL
);


ALTER TABLE practica.core_sessioentrenament_exercicis OWNER TO est_e7864955;

--
-- Name: core_sessioentrenament_exercicis_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_sessioentrenament_exercicis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_sessioentrenament_exercicis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_sessioentrenament_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_sessioentrenament ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_sessioentrenament_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_ubicacio; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_ubicacio (
    id bigint NOT NULL,
    tipus_ubicacio character varying(10) NOT NULL,
    adreca character varying(200) NOT NULL
);


ALTER TABLE practica.core_ubicacio OWNER TO est_e7864955;

--
-- Name: core_ubicacio_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_ubicacio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_ubicacio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_valoracio; Type: TABLE; Schema: practica; Owner: est_e7864955
--

CREATE TABLE practica.core_valoracio (
    id bigint NOT NULL,
    valoracio double precision NOT NULL,
    comentaris text,
    atleta_id character varying(20) NOT NULL,
    ubicacio_id bigint NOT NULL
);


ALTER TABLE practica.core_valoracio OWNER TO est_e7864955;

--
-- Name: core_valoracio_id_seq; Type: SEQUENCE; Schema: practica; Owner: est_e7864955
--

ALTER TABLE practica.core_valoracio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME practica.core_valoracio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_alimentacio core_alimentacio_atleta_id_key; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_alimentacio
    ADD CONSTRAINT core_alimentacio_atleta_id_key UNIQUE (atleta_id);


--
-- Name: core_alimentacio core_alimentacio_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_alimentacio
    ADD CONSTRAINT core_alimentacio_pkey PRIMARY KEY (id);


--
-- Name: core_atleta core_atleta_correu_key; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_atleta
    ADD CONSTRAINT core_atleta_correu_key UNIQUE (correu);


--
-- Name: core_atleta core_atleta_numero_telefon_key; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_atleta
    ADD CONSTRAINT core_atleta_numero_telefon_key UNIQUE (numero_telefon);


--
-- Name: core_atleta core_atleta_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_atleta
    ADD CONSTRAINT core_atleta_pkey PRIMARY KEY (dni_atleta);


--
-- Name: core_descans core_descans_atleta_id_data_inici_b9618892_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_descans
    ADD CONSTRAINT core_descans_atleta_id_data_inici_b9618892_uniq UNIQUE (atleta_id, data_inici);


--
-- Name: core_descans core_descans_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_descans
    ADD CONSTRAINT core_descans_pkey PRIMARY KEY (id);


--
-- Name: core_exercici core_exercici_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_exercici
    ADD CONSTRAINT core_exercici_pkey PRIMARY KEY (id);


--
-- Name: core_forca core_forca_exercici_id_num_serie_f008c76e_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_forca
    ADD CONSTRAINT core_forca_exercici_id_num_serie_f008c76e_uniq UNIQUE (exercici_id, num_serie);


--
-- Name: core_forca core_forca_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_forca
    ADD CONSTRAINT core_forca_pkey PRIMARY KEY (id);


--
-- Name: core_informeia core_informeia_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_informeia
    ADD CONSTRAINT core_informeia_pkey PRIMARY KEY (id);


--
-- Name: core_informeia core_informeia_registre_diari_id_key; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_informeia
    ADD CONSTRAINT core_informeia_registre_diari_id_key UNIQUE (registre_diari_id);


--
-- Name: core_lesio core_lesio_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_lesio
    ADD CONSTRAINT core_lesio_pkey PRIMARY KEY (id);


--
-- Name: core_registrediari core_registrediari_atleta_id_data_0ad7fd7f_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_registrediari
    ADD CONSTRAINT core_registrediari_atleta_id_data_0ad7fd7f_uniq UNIQUE (atleta_id, data);


--
-- Name: core_registrediari core_registrediari_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_registrediari
    ADD CONSTRAINT core_registrediari_pkey PRIMARY KEY (id);


--
-- Name: core_resistencia core_resistencia_exercici_id_num_serie_9a51e40a_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_resistencia
    ADD CONSTRAINT core_resistencia_exercici_id_num_serie_9a51e40a_uniq UNIQUE (exercici_id, num_serie);


--
-- Name: core_resistencia core_resistencia_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_resistencia
    ADD CONSTRAINT core_resistencia_pkey PRIMARY KEY (id);


--
-- Name: core_sessioentrenament_exercicis core_sessioentrenament_e_sessioentrenament_id_exe_8174b8c6_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament_exercicis
    ADD CONSTRAINT core_sessioentrenament_e_sessioentrenament_id_exe_8174b8c6_uniq UNIQUE (sessioentrenament_id, exercici_id);


--
-- Name: core_sessioentrenament_exercicis core_sessioentrenament_exercicis_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament_exercicis
    ADD CONSTRAINT core_sessioentrenament_exercicis_pkey PRIMARY KEY (id);


--
-- Name: core_sessioentrenament core_sessioentrenament_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament
    ADD CONSTRAINT core_sessioentrenament_pkey PRIMARY KEY (id);


--
-- Name: core_ubicacio core_ubicacio_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_ubicacio
    ADD CONSTRAINT core_ubicacio_pkey PRIMARY KEY (id);


--
-- Name: core_valoracio core_valoracio_atleta_id_ubicacio_id_670f7d46_uniq; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_valoracio
    ADD CONSTRAINT core_valoracio_atleta_id_ubicacio_id_670f7d46_uniq UNIQUE (atleta_id, ubicacio_id);


--
-- Name: core_valoracio core_valoracio_pkey; Type: CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_valoracio
    ADD CONSTRAINT core_valoracio_pkey PRIMARY KEY (id);


--
-- Name: core_alimentacio_atleta_id_c2962c0d_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_alimentacio_atleta_id_c2962c0d_like ON practica.core_alimentacio USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_atleta_correu_1c0c0815_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_atleta_correu_1c0c0815_like ON practica.core_atleta USING btree (correu varchar_pattern_ops);


--
-- Name: core_atleta_dni_atleta_55f9e5e1_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_atleta_dni_atleta_55f9e5e1_like ON practica.core_atleta USING btree (dni_atleta varchar_pattern_ops);


--
-- Name: core_atleta_numero_telefon_0ec0df7a_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_atleta_numero_telefon_0ec0df7a_like ON practica.core_atleta USING btree (numero_telefon varchar_pattern_ops);


--
-- Name: core_descans_atleta_id_8f6cd13f; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_descans_atleta_id_8f6cd13f ON practica.core_descans USING btree (atleta_id);


--
-- Name: core_descans_atleta_id_8f6cd13f_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_descans_atleta_id_8f6cd13f_like ON practica.core_descans USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_exercici_atleta_id_b675a120; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_exercici_atleta_id_b675a120 ON practica.core_exercici USING btree (atleta_id);


--
-- Name: core_exercici_atleta_id_b675a120_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_exercici_atleta_id_b675a120_like ON practica.core_exercici USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_forca_exercici_id_7e83a906; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_forca_exercici_id_7e83a906 ON practica.core_forca USING btree (exercici_id);


--
-- Name: core_lesio_atleta_id_9c96e935; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_lesio_atleta_id_9c96e935 ON practica.core_lesio USING btree (atleta_id);


--
-- Name: core_lesio_atleta_id_9c96e935_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_lesio_atleta_id_9c96e935_like ON practica.core_lesio USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_registrediari_atleta_id_29dc04a1; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_registrediari_atleta_id_29dc04a1 ON practica.core_registrediari USING btree (atleta_id);


--
-- Name: core_registrediari_atleta_id_29dc04a1_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_registrediari_atleta_id_29dc04a1_like ON practica.core_registrediari USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_resistencia_exercici_id_0e4fb5a7; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_resistencia_exercici_id_0e4fb5a7 ON practica.core_resistencia USING btree (exercici_id);


--
-- Name: core_sessioentrenament_atleta_id_993d7648; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_sessioentrenament_atleta_id_993d7648 ON practica.core_sessioentrenament USING btree (atleta_id);


--
-- Name: core_sessioentrenament_atleta_id_993d7648_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_sessioentrenament_atleta_id_993d7648_like ON practica.core_sessioentrenament USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_sessioentrenament_exercicis_exercici_id_b74164b2; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_sessioentrenament_exercicis_exercici_id_b74164b2 ON practica.core_sessioentrenament_exercicis USING btree (exercici_id);


--
-- Name: core_sessioentrenament_exercicis_sessioentrenament_id_f995728c; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_sessioentrenament_exercicis_sessioentrenament_id_f995728c ON practica.core_sessioentrenament_exercicis USING btree (sessioentrenament_id);


--
-- Name: core_sessioentrenament_ubicacio_id_383ac9c7; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_sessioentrenament_ubicacio_id_383ac9c7 ON practica.core_sessioentrenament USING btree (ubicacio_id);


--
-- Name: core_valoracio_atleta_id_d18ea80a; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_valoracio_atleta_id_d18ea80a ON practica.core_valoracio USING btree (atleta_id);


--
-- Name: core_valoracio_atleta_id_d18ea80a_like; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_valoracio_atleta_id_d18ea80a_like ON practica.core_valoracio USING btree (atleta_id varchar_pattern_ops);


--
-- Name: core_valoracio_ubicacio_id_8916627f; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX core_valoracio_ubicacio_id_8916627f ON practica.core_valoracio USING btree (ubicacio_id);


--
-- Name: idx_ubicacio_upper; Type: INDEX; Schema: practica; Owner: est_e7864955
--

CREATE INDEX idx_ubicacio_upper ON practica.core_ubicacio USING btree (upper((tipus_ubicacio)::text));


--
-- Name: core_alimentacio core_alimentacio_atleta_id_c2962c0d_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_alimentacio
    ADD CONSTRAINT core_alimentacio_atleta_id_c2962c0d_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_descans core_descans_atleta_id_8f6cd13f_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_descans
    ADD CONSTRAINT core_descans_atleta_id_8f6cd13f_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_exercici core_exercici_atleta_id_b675a120_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_exercici
    ADD CONSTRAINT core_exercici_atleta_id_b675a120_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_forca core_forca_exercici_id_7e83a906_fk_core_exercici_id; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_forca
    ADD CONSTRAINT core_forca_exercici_id_7e83a906_fk_core_exercici_id FOREIGN KEY (exercici_id) REFERENCES practica.core_exercici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_informeia core_informeia_registre_diari_id_052a2c79_fk_core_regi; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_informeia
    ADD CONSTRAINT core_informeia_registre_diari_id_052a2c79_fk_core_regi FOREIGN KEY (registre_diari_id) REFERENCES practica.core_registrediari(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_lesio core_lesio_atleta_id_9c96e935_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_lesio
    ADD CONSTRAINT core_lesio_atleta_id_9c96e935_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_registrediari core_registrediari_atleta_id_29dc04a1_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_registrediari
    ADD CONSTRAINT core_registrediari_atleta_id_29dc04a1_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_resistencia core_resistencia_exercici_id_0e4fb5a7_fk_core_exercici_id; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_resistencia
    ADD CONSTRAINT core_resistencia_exercici_id_0e4fb5a7_fk_core_exercici_id FOREIGN KEY (exercici_id) REFERENCES practica.core_exercici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_sessioentrenament core_sessioentrename_atleta_id_993d7648_fk_core_atle; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament
    ADD CONSTRAINT core_sessioentrename_atleta_id_993d7648_fk_core_atle FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_sessioentrenament_exercicis core_sessioentrename_exercici_id_b74164b2_fk_core_exer; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament_exercicis
    ADD CONSTRAINT core_sessioentrename_exercici_id_b74164b2_fk_core_exer FOREIGN KEY (exercici_id) REFERENCES practica.core_exercici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_sessioentrenament_exercicis core_sessioentrename_sessioentrenament_id_f995728c_fk_core_sess; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament_exercicis
    ADD CONSTRAINT core_sessioentrename_sessioentrenament_id_f995728c_fk_core_sess FOREIGN KEY (sessioentrenament_id) REFERENCES practica.core_sessioentrenament(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_sessioentrenament core_sessioentrenament_ubicacio_id_383ac9c7_fk_core_ubicacio_id; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_sessioentrenament
    ADD CONSTRAINT core_sessioentrenament_ubicacio_id_383ac9c7_fk_core_ubicacio_id FOREIGN KEY (ubicacio_id) REFERENCES practica.core_ubicacio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_valoracio core_valoracio_atleta_id_d18ea80a_fk_core_atleta_dni_atleta; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_valoracio
    ADD CONSTRAINT core_valoracio_atleta_id_d18ea80a_fk_core_atleta_dni_atleta FOREIGN KEY (atleta_id) REFERENCES practica.core_atleta(dni_atleta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_valoracio core_valoracio_ubicacio_id_8916627f_fk_core_ubicacio_id; Type: FK CONSTRAINT; Schema: practica; Owner: est_e7864955
--

ALTER TABLE ONLY practica.core_valoracio
    ADD CONSTRAINT core_valoracio_ubicacio_id_8916627f_fk_core_ubicacio_id FOREIGN KEY (ubicacio_id) REFERENCES practica.core_ubicacio(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict O6BK9XoUyBC1GMh5NzAAP40OAn8ANpLhLV518kGEVcQ1kyDwpS0AxTEfHfH9PvQ

