# Generated by Django 6.0.5 on 2026-05-13 21:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "dni_atleta",
                    models.CharField(
                        help_text="Document d'identitat (ex. 12345678X)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom complet de l'atleta", max_length=100
                    ),
                ),
                ("data_naixement", models.DateField(help_text="Format: AAAA-MM-DD")),
                (
                    "correu",
                    models.EmailField(
                        help_text="Adreça de correu electrònic vàlida",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "numero_telefon",
                    models.CharField(
                        help_text="Telèfon de contacte amb prefix",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "pes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pes en kilograms (kg)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "composicio_corporal",
                    models.CharField(
                        help_text="Ex: 15% greix, 45% massa muscular", max_length=200
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Altura en metres (ex: 1.80)",
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "objectiu",
                    models.CharField(
                        help_text="Objectiu principal (ex. Guanyar massa muscular, Pèrdua de pes)",
                        max_length=100,
                    ),
                ),
                (
                    "activitat_fisica_diaria",
                    models.CharField(
                        choices=[
                            ("SEDENTARI", "Sedentari"),
                            ("ACTIU", "Actiu"),
                            ("MOLT_ACTIU", "Molt Actiu"),
                        ],
                        help_text="Nivell d'activitat diària fora de l'entrenament",
                        max_length=15,
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[("ACTIU", "Actiu"), ("LESIONAT", "Lesionat")],
                        help_text="Estat general actual de l'atleta",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Atletes",
            },
        ),
        migrations.CreateModel(
            name="Ubicacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipus_ubicacio",
                    models.CharField(
                        choices=[("EXTERIOR", "Exterior"), ("INTERIOR", "Interior")],
                        help_text="Lloc on es realitza l'entrenament",
                        max_length=10,
                    ),
                ),
                (
                    "adreca",
                    models.CharField(
                        help_text="Nom del gimnàs, parc o adreça exacta", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ubicacions",
            },
        ),
        migrations.CreateModel(
            name="Alimentacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipus_alimentacio",
                    models.CharField(
                        choices=[
                            ("VEGETARIA", "Vegetarià"),
                            ("VEGA", "Vegà"),
                            ("OMNIVOR", "Omnívor"),
                        ],
                        help_text="Preferència dietètica",
                        max_length=15,
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Objectiu calòric diari (kcal)",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "proteina",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grams de proteïna diaris (g)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "carbohidrats",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grams de carbohidrats diaris (g)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "grases",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grams de greixos diaris (g)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "suplementacio",
                    models.TextField(
                        blank=True,
                        help_text="Llista de suplements (opcional)",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.OneToOneField(
                        help_text="Atleta a qui pertany aquesta dieta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="alimentacio",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Alimentacions",
            },
        ),
        migrations.CreateModel(
            name="Exercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom descriptiu de l'exercici", max_length=100
                    ),
                ),
                (
                    "descripcio",
                    models.TextField(
                        blank=True,
                        help_text="Instruccions tècniques de l'exercici",
                        null=True,
                    ),
                ),
                (
                    "descans_entre_series",
                    models.DurationField(
                        blank=True,
                        help_text="Temps de descans suggerit (Format: HH:MM:SS)",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Creador de l'exercici",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicis",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Exercicis",
            },
        ),
        migrations.CreateModel(
            name="Forca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_serie",
                    models.PositiveIntegerField(
                        help_text="Número d'ordre d'aquesta sèrie"
                    ),
                ),
                (
                    "grup_muscular",
                    models.CharField(
                        help_text="Múscul o grup muscular principal", max_length=100
                    ),
                ),
                (
                    "pes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Càrrega en kilograms (kg)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "rpe",
                    models.PositiveIntegerField(
                        help_text="Percepció de l'esforç de 0 a 10 (Rate of Perceived Exertion)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "exercici",
                    models.ForeignKey(
                        help_text="Exercici al qual pertany la sèrie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="core.exercici",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sèries de Força",
            },
        ),
        migrations.CreateModel(
            name="Lesio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inici",
                    models.DateField(
                        help_text="Data en què es va produir o diagnosticar (Format: AAAA-MM-DD)"
                    ),
                ),
                (
                    "data_fi",
                    models.DateField(
                        blank=True,
                        help_text="Data de curació total. Deixar en blanc si encara està activa. (Format: AAAA-MM-DD)",
                        null=True,
                    ),
                ),
                (
                    "zona_afectada",
                    models.CharField(
                        help_text="Part del cos lesionada (ex. Genoll dret, Espatlla)",
                        max_length=100,
                    ),
                ),
                (
                    "grau_serietat",
                    models.PositiveIntegerField(
                        help_text="Escala de gravetat de 0 (lleu) a 5 (molt greu)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "estat_actual",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("REHABILITACIO", "Rehabilitació"),
                            ("RESOLTA", "Resolta"),
                        ],
                        help_text="Estat de recuperació de la lesió",
                        max_length=15,
                    ),
                ),
                (
                    "comentaris_diagnostic",
                    models.TextField(
                        blank=True,
                        help_text="Diagnòstic mèdic o descripció detallada",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Atleta que pateix la lesió",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesions",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lesions",
            },
        ),
        migrations.CreateModel(
            name="RegistreDiari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Data del registre (per defecte avui)",
                    ),
                ),
                (
                    "adaptabilitat_alimentacio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentatge d'adherència a la dieta establerta (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "comentaris_entrenaments",
                    models.TextField(
                        blank=True,
                        help_text="Comentaris sobre l'esforç, la motivació o incidents",
                        null=True,
                    ),
                ),
                (
                    "estat_recuperacio_descans",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Sensació de recuperació al despertar (0.0 a 5.0)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "nivell_energia",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Nivell d'energia percebut durant el dia (0.0 a 5.0)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "nivell_estres",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Nivell d'estrès emocional o físic (0.0 a 5.0)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "sensacions_generals",
                    models.TextField(
                        blank=True,
                        help_text="Notes generals, dolors, estat d'ànim, etc.",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Atleta que omple el registre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registres",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Registres Diaris",
                "unique_together": {("atleta", "data")},
            },
        ),
        migrations.CreateModel(
            name="InformeIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recomanacio_entrenament",
                    models.TextField(
                        help_text="Anàlisi i suggeriments d'entrenament generats per l'IA"
                    ),
                ),
                (
                    "recomanacio_alimentacio",
                    models.TextField(
                        help_text="Anàlisi i suggeriments d'alimentació generats per l'IA"
                    ),
                ),
                (
                    "recomanacio_descans",
                    models.TextField(
                        help_text="Anàlisi i suggeriments de descans generats per l'IA"
                    ),
                ),
                (
                    "registre_diari",
                    models.OneToOneField(
                        help_text="Registre diari al qual s'associa aquest informe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informeIA",
                        to="core.registrediari",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Informes IA",
            },
        ),
        migrations.CreateModel(
            name="Resistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_serie",
                    models.PositiveIntegerField(
                        help_text="Número d'ordre d'aquesta sèrie"
                    ),
                ),
                (
                    "duracio",
                    models.DurationField(
                        help_text="Duració d'aquesta sèrie (Format: HH:MM:SS)"
                    ),
                ),
                (
                    "tipus_superficie",
                    models.CharField(
                        choices=[
                            ("ASFALT", "Asfalt"),
                            ("CINTA", "Cinta"),
                            ("TRAIL", "Trail"),
                        ],
                        help_text="Terreny on s'ha realitzat",
                        max_length=10,
                    ),
                ),
                (
                    "distancia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distància recorreguda en kilòmetres (km)",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "desnivell",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Desnivell positiu acumulat en metres (m)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "freq_cardiaca_mitjana",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Mitjana de pulsacions per minut (bpm)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
                (
                    "exercici",
                    models.ForeignKey(
                        help_text="Exercici al qual pertany la sèrie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="core.exercici",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sèries de Resistència",
            },
        ),
        migrations.CreateModel(
            name="SessioEntrenament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        help_text="Data de la sessió d'entrenament (Format: AAAA-MM-DD)"
                    ),
                ),
                (
                    "duracio_total",
                    models.DurationField(
                        help_text="Duració completa de l'entrenament (Format: HH:MM:SS)"
                    ),
                ),
                (
                    "comentaris",
                    models.TextField(
                        blank=True,
                        help_text="Sensacions i notes de l'entrenament",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Atleta que realitza la sessió",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.atleta",
                    ),
                ),
                (
                    "exercicis",
                    models.ManyToManyField(
                        help_text="Llista d'exercicis a realitzar en aquesta sessió",
                        related_name="sessions",
                        to="core.exercici",
                    ),
                ),
                (
                    "ubicacio",
                    models.ForeignKey(
                        help_text="Lloc de la sessió",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ubicacio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sessions d'entrenament",
            },
        ),
        migrations.CreateModel(
            name="Descans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inici",
                    models.DateTimeField(help_text="Dia i hora d'anar a dormir"),
                ),
                (
                    "duracio",
                    models.PositiveIntegerField(
                        help_text="Duració total de la sessió de son en minuts"
                    ),
                ),
                (
                    "despert",
                    models.PositiveIntegerField(
                        help_text="Temps despert durant la nit en minuts"
                    ),
                ),
                (
                    "rem",
                    models.PositiveIntegerField(
                        help_text="Temps en fase REM en minuts"
                    ),
                ),
                (
                    "core",
                    models.PositiveIntegerField(
                        help_text="Temps en fase de son lleuger (Core) en minuts"
                    ),
                ),
                (
                    "deep",
                    models.PositiveIntegerField(
                        help_text="Temps en fase de son profund (Deep) en minuts"
                    ),
                ),
                (
                    "hrv",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variabilitat de la Freqüència Cardíaca en mil·lisegons (ms)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Atleta al qual pertany aquest registre de son",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descansos",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Descansos",
                "unique_together": {("atleta", "data_inici")},
            },
        ),
        migrations.CreateModel(
            name="Valoracio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valoracio",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Puntuació del 0.0 al 5.0",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "comentaris",
                    models.TextField(
                        blank=True,
                        help_text="Comentaris sobre les instal·lacions",
                        null=True,
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        help_text="Atleta que fa la valoració",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.atleta",
                    ),
                ),
                (
                    "ubicacio",
                    models.ForeignKey(
                        help_text="Ubicació valorada",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ubicacio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Valoracions",
                "unique_together": {("atleta", "ubicacio")},
            },
        ),
    ]
