# Generated by Django 6.0.5 on 2026-05-07 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "dni_atleta",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
                ("data_naixement", models.DateField()),
                ("correu", models.EmailField(max_length=150, unique=True)),
                ("numero_telefon", models.CharField(max_length=20, unique=True)),
                (
                    "pes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("composicio_corporal", models.CharField(max_length=200)),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("objectiu", models.CharField(max_length=100)),
                (
                    "activitat_fisica_diaria",
                    models.CharField(
                        choices=[
                            ("SEDENTARI", "Sedentari"),
                            ("ACTIU", "Actiu"),
                            ("MOLT_ACTIU", "Molt Actiu"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "estat",
                    models.CharField(
                        choices=[("ACTIU", "Actiu"), ("LESIONAT", "Lesionat")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_serie", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RegistreDiari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "adaptabilitat_alimentacio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("comentaris_entrenaments", models.TextField(blank=True, null=True)),
                (
                    "estat_recuperacio_descans",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "nivell_energia",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "nivell_estres",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("sensacions_generals", models.TextField(blank=True, null=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registres_diaris",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "unique_together": {("atleta", "data")},
            },
        ),
        migrations.CreateModel(
            name="Ubicacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipus_ubicacio",
                    models.CharField(
                        choices=[("EXTERIOR", "Exterior"), ("INTERIOR", "Interior")],
                        max_length=10,
                    ),
                ),
                ("adreca", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Alimentacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipus_alimentacio",
                    models.CharField(
                        choices=[
                            ("VEGETARIA", "Vegetarià"),
                            ("VEGA", "Vegà"),
                            ("OMNIVOR", "Omnívor"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "proteina",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "carbohidrats",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "grases",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("suplementacio", models.TextField(blank=True, null=True)),
                (
                    "atleta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alimentacio",
                        to="core.atleta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("descripcio", models.TextField(blank=True, null=True)),
                ("descans_entre_series", models.DurationField(blank=True, null=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercicis_creats",
                        to="core.atleta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forca",
            fields=[
                (
                    "serie_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.serie",
                    ),
                ),
                ("grup_muscular", models.CharField(max_length=100)),
                (
                    "pes",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "rpe",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
            bases=("core.serie",),
        ),
        migrations.CreateModel(
            name="Resistencia",
            fields=[
                (
                    "serie_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.serie",
                    ),
                ),
                ("duracio", models.DurationField()),
                (
                    "tipus_superficie",
                    models.CharField(
                        choices=[
                            ("ASFALT", "Asfalt"),
                            ("CINTA", "Cinta"),
                            ("TRAIL", "Trail"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "distancia",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "desnivell",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "freq_cardiaca_mitjana",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
            ],
            bases=("core.serie",),
        ),
        migrations.AddField(
            model_name="serie",
            name="exercici",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="core.exercici",
            ),
        ),
        migrations.CreateModel(
            name="InformeIA",
            fields=[
                (
                    "registre_diari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="informe_ia",
                        serialize=False,
                        to="core.registrediari",
                    ),
                ),
                ("recomanacio_entrenament", models.TextField()),
                ("recomanacio_alimentacio", models.TextField()),
                ("recomanacio_descans", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Lesio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inici", models.DateField()),
                ("data_fi", models.DateField(blank=True, null=True)),
                ("zona_afectada", models.CharField(max_length=100)),
                (
                    "grau_serietat",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "estat_actual",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("REHABILITACIO", "Rehabilitació"),
                            ("RESOLTA", "Resolta"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comentaris_diagnostic", models.TextField(blank=True, null=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesions",
                        to="core.atleta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessioEntrenament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("duracio_total", models.DurationField()),
                ("comentaris", models.TextField(blank=True, null=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.atleta"
                    ),
                ),
                (
                    "exercicis",
                    models.ManyToManyField(related_name="sessions", to="core.exercici"),
                ),
                (
                    "ubicacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.ubicacio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Descans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inici", models.DateTimeField()),
                ("duracio", models.PositiveIntegerField(help_text="En minuts")),
                ("despert", models.PositiveIntegerField()),
                ("rem", models.PositiveIntegerField()),
                ("core", models.PositiveIntegerField()),
                ("deep", models.PositiveIntegerField()),
                (
                    "hrv",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descansos",
                        to="core.atleta",
                    ),
                ),
            ],
            options={
                "unique_together": {("atleta", "data_inici")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="serie",
            unique_together={("exercici", "num_serie")},
        ),
        migrations.CreateModel(
            name="Valoracio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valoracio",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("comentaris", models.TextField(blank=True, null=True)),
                (
                    "atleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.atleta"
                    ),
                ),
                (
                    "ubicacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.ubicacio"
                    ),
                ),
            ],
            options={
                "unique_together": {("atleta", "ubicacio")},
            },
        ),
    ]
