# Generated by Django 6.0.5 on 2026-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesio",
            name="id_lesio",
            field=models.IntegerField(
                default=1, help_text="Identificador de la lesió propi de l'atleta"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesio",
            unique_together={("atleta", "id_lesio")},
        ),
    ]
