# Generated by Django 6.0.5 on 2026-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrediari",
            name="data",
            field=models.DateField(auto_now_add=True),
        ),
    ]
