# Generated by Django 6.0.5 on 2026-06-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lesio_id_lesio_alter_lesio_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentacio",
            name="atleta",
            field=models.OneToOneField(
                help_text="Atleta a qui pertany aquesta dieta",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alimentacio",
                to="core.atleta",
            ),
        ),
    ]
