# Generated by Django 6.0.5 on 2026-05-08 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_registrediari_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentacio",
            name="atleta",
            field=models.OneToOneField(
                help_text="Atleta a qui pertany aquesta dieta",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alimentacio",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Objectiu calòric diari (kcal)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="carbohidrats",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Grams de carbohidrats diaris (g)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="grases",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Grams de greixos diaris (g)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="proteina",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Grams de proteïna diaris (g)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="suplementacio",
            field=models.TextField(
                blank=True, help_text="Llista de suplements (opcional)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="alimentacio",
            name="tipus_alimentacio",
            field=models.CharField(
                choices=[
                    ("VEGETARIA", "Vegetarià"),
                    ("VEGA", "Vegà"),
                    ("OMNIVOR", "Omnívor"),
                ],
                help_text="Preferència dietètica",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="activitat_fisica_diaria",
            field=models.CharField(
                choices=[
                    ("SEDENTARI", "Sedentari"),
                    ("ACTIU", "Actiu"),
                    ("MOLT_ACTIU", "Molt Actiu"),
                ],
                help_text="Nivell d'activitat diària fora de l'entrenament",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="altura",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Altura en metres (ex: 1.80)",
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="composicio_corporal",
            field=models.CharField(
                help_text="Ex: 15% greix, 45% massa muscular", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="correu",
            field=models.EmailField(
                help_text="Adreça de correu electrònic vàlida",
                max_length=150,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="data_naixement",
            field=models.DateField(help_text="Format: AAAA-MM-DD"),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="dni_atleta",
            field=models.CharField(
                help_text="Document d'identitat (ex. 12345678X)",
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="estat",
            field=models.CharField(
                choices=[("ACTIU", "Actiu"), ("LESIONAT", "Lesionat")],
                help_text="Estat general actual de l'atleta",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="nom",
            field=models.CharField(help_text="Nom complet de l'atleta", max_length=100),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="numero_telefon",
            field=models.CharField(
                help_text="Telèfon de contacte amb prefix", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="objectiu",
            field=models.CharField(
                help_text="Objectiu principal (ex. Guanyar massa muscular, Pèrdua de pes)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="atleta",
            name="pes",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Pes en kilograms (kg)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="atleta",
            field=models.ForeignKey(
                help_text="Atleta al qual pertany aquest registre de son",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descansos",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="core",
            field=models.PositiveIntegerField(
                help_text="Temps en fase de son lleuger (Core) en minuts"
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="data_inici",
            field=models.DateTimeField(help_text="Dia i hora d'anar a dormir"),
        ),
        migrations.AlterField(
            model_name="descans",
            name="deep",
            field=models.PositiveIntegerField(
                help_text="Temps en fase de son profund (Deep) en minuts"
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="despert",
            field=models.PositiveIntegerField(
                help_text="Temps despert durant la nit en minuts"
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="duracio",
            field=models.PositiveIntegerField(
                help_text="Duració total de la sessió de son en minuts"
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="hrv",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Variabilitat de la Freqüència Cardíaca en mil·lisegons (ms)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="descans",
            name="rem",
            field=models.PositiveIntegerField(help_text="Temps en fase REM en minuts"),
        ),
        migrations.AlterField(
            model_name="exercici",
            name="atleta",
            field=models.ForeignKey(
                help_text="Creador de l'exercici",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercicis",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="exercici",
            name="descans_entre_series",
            field=models.DurationField(
                blank=True,
                help_text="Temps de descans suggerit (Format: HH:MM:SS)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exercici",
            name="descripcio",
            field=models.TextField(
                blank=True, help_text="Instruccions tècniques de l'exercici", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exercici",
            name="nom",
            field=models.CharField(
                help_text="Nom descriptiu de l'exercici", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="grup_muscular",
            field=models.CharField(
                help_text="Múscul o grup muscular principal", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="num_serie",
            field=models.PositiveIntegerField(
                help_text="Número d'ordre d'aquesta sèrie"
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="pes",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Càrrega en kilograms (kg)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="rpe",
            field=models.PositiveIntegerField(
                help_text="Percepció de l'esforç de 0 a 10 (Rate of Perceived Exertion)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informeia",
            name="recomanacio_alimentacio",
            field=models.TextField(
                help_text="Anàlisi i suggeriments d'alimentació generats per l'IA"
            ),
        ),
        migrations.AlterField(
            model_name="informeia",
            name="recomanacio_descans",
            field=models.TextField(
                help_text="Anàlisi i suggeriments de descans generats per l'IA"
            ),
        ),
        migrations.AlterField(
            model_name="informeia",
            name="recomanacio_entrenament",
            field=models.TextField(
                help_text="Anàlisi i suggeriments d'entrenament generats per l'IA"
            ),
        ),
        migrations.AlterField(
            model_name="informeia",
            name="registre_diari",
            field=models.OneToOneField(
                help_text="Registre diari al qual s'associa aquest informe",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="informeIA",
                serialize=False,
                to="core.registrediari",
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="atleta",
            field=models.ForeignKey(
                help_text="Atleta que pateix la lesió",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesions",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="comentaris_diagnostic",
            field=models.TextField(
                blank=True,
                help_text="Diagnòstic mèdic o descripció detallada",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="data_fi",
            field=models.DateField(
                blank=True,
                help_text="Data de curació total. Deixar en blanc si encara està activa. (Format: AAAA-MM-DD)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="data_inici",
            field=models.DateField(
                help_text="Data en què es va produir o diagnosticar (Format: AAAA-MM-DD)"
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="estat_actual",
            field=models.CharField(
                choices=[
                    ("ACTIVA", "Activa"),
                    ("REHABILITACIO", "Rehabilitació"),
                    ("RESOLTA", "Resolta"),
                ],
                help_text="Estat de recuperació de la lesió",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="grau_serietat",
            field=models.PositiveIntegerField(
                help_text="Escala de gravetat de 0 (lleu) a 5 (molt greu)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lesio",
            name="zona_afectada",
            field=models.CharField(
                help_text="Part del cos lesionada (ex. Genoll dret, Espatlla)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="adaptabilitat_alimentacio",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percentatge d'adherència a la dieta establerta (0-100%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="atleta",
            field=models.ForeignKey(
                help_text="Atleta que omple el registre",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registres",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="comentaris_entrenaments",
            field=models.TextField(
                blank=True,
                help_text="Comentaris sobre l'esforç, la motivació o incidents",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="data",
            field=models.DateField(
                auto_now_add=True,
                help_text="Data de creació (Assignada automàticament a avui)",
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="estat_recuperacio_descans",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Sensació de recuperació al despertar (0.0 a 5.0)",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="nivell_energia",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Nivell d'energia percebut durant el dia (0.0 a 5.0)",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="nivell_estres",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Nivell d'estrès emocional o físic (0.0 a 5.0)",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registrediari",
            name="sensacions_generals",
            field=models.TextField(
                blank=True,
                help_text="Notes generals, dolors, estat d'ànim, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="desnivell",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Desnivell positiu acumulat en metres (m)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="distancia",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Distància recorreguda en kilòmetres (km)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="duracio",
            field=models.DurationField(
                help_text="Duració d'aquesta sèrie (Format: HH:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="freq_cardiaca_mitjana",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Mitjana de pulsacions per minut (bpm)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(220),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="num_serie",
            field=models.PositiveIntegerField(
                help_text="Número d'ordre d'aquesta sèrie"
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="tipus_superficie",
            field=models.CharField(
                choices=[("ASFALT", "Asfalt"), ("CINTA", "Cinta"), ("TRAIL", "Trail")],
                help_text="Terreny on s'ha realitzat",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="atleta",
            field=models.ForeignKey(
                help_text="Atleta que realitza la sessió",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="comentaris",
            field=models.TextField(
                blank=True, help_text="Sensacions i notes de l'entrenament", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="data",
            field=models.DateField(
                help_text="Data de la sessió d'entrenament (Format: AAAA-MM-DD)"
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="duracio_total",
            field=models.DurationField(
                help_text="Duració completa de l'entrenament (Format: HH:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="exercicis",
            field=models.ManyToManyField(
                help_text="Llista d'exercicis a realitzar en aquesta sessió",
                related_name="sessions",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="ubicacio",
            field=models.ForeignKey(
                help_text="Lloc de la sessió",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ubicacio",
            ),
        ),
        migrations.AlterField(
            model_name="ubicacio",
            name="adreca",
            field=models.CharField(
                help_text="Nom del gimnàs, parc o adreça exacta", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="ubicacio",
            name="tipus_ubicacio",
            field=models.CharField(
                choices=[("EXTERIOR", "Exterior"), ("INTERIOR", "Interior")],
                help_text="Lloc on es realitza l'entrenament",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="valoracio",
            name="atleta",
            field=models.ForeignKey(
                help_text="Atleta que fa la valoració",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="valoracio",
            name="comentaris",
            field=models.TextField(
                blank=True, help_text="Comentaris sobre les instal·lacions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="valoracio",
            name="ubicacio",
            field=models.ForeignKey(
                help_text="Ubicació valorada",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ubicacio",
            ),
        ),
        migrations.AlterField(
            model_name="valoracio",
            name="valoracio",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Puntuació del 0.0 al 5.0",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
