# Generated by Django 6.0.5 on 2026-05-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_alimentacio_atleta_alter_alimentacio_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentacio",
            name="atleta",
            field=models.OneToOneField(
                help_text="Atleta a qui pertany aquesta dieta",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="alimentacio",
                to="core.atleta",
            ),
        ),
        migrations.AlterField(
            model_name="forca",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="informeia",
            name="registre_diari",
            field=models.OneToOneField(
                help_text="Registre diari al qual s'associa aquest informe",
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                related_name="informeIA",
                serialize=False,
                to="core.registrediari",
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="sessioentrenament",
            name="ubicacio",
            field=models.ForeignKey(
                help_text="Lloc de la sessió",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ubicacio",
            ),
        ),
    ]
