# Generated by Django 6.0.5 on 2026-05-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_alimentacio_atleta_alter_forca_exercici_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forca",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
        migrations.AlterField(
            model_name="resistencia",
            name="exercici",
            field=models.ForeignKey(
                help_text="Exercici al qual pertany la sèrie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="core.exercici",
            ),
        ),
    ]
